### PR TITLE
Update version

### PR DESCRIPTION
**Pull request by rragundez**
Update version for last pull request. This is relevant for people installing the package from the github repo (since the latest update is not in a CRAN package). If install from github then the version will be higher than the one in the CRAN repository hence it will keep the latest version and not override the old version from the CRAN. Once CRAN is up to date it will just work installing the newest version.

### CODE REVIEW

**Comment by sorhawell** [comment]
Hi @rragundez , I just tested your claim, it doesn't seem like it to me. I installed cran version and then the github version and I check if your latest contribution is included, it is. Am I missing something?

```
#remove forestFloor
remove.packages("forestFloor")

#install cran
install.packages("forestFloor")

#overwite with github bleeding edge (Rtools required for windows)
library(devtools)
install_github("sorhawell/forestFloor")

#load library
library(forestFloor)

#your last pull request changes is present in installed version from github
deparse(forestFloor::Xtestmerger)[15:20]

[1] "    if (any(!namesCheck)) "                                                                                         
[2] "        stop(paste(\"column(s)\", which(!namesCheck), \"in Xtest and X has names mismatch. Col names must match\"))"
[3] "    factor.ind = which(sapply(X, is.factor))"                                                                       
[4] "    unmatchedTestLevels = mapply(FUN = function(xl, tl) tl[which(is.na(match(tl, "                                  
[5] "        xl)))], lapply(X[factor.ind], levels), lapply(test[factor.ind], "                                           
[6] "        levels), SIMPLIFY = FALSE, USE.NAMES = TRUE)"    
````

**Comment by rragundez** [comment]
What I meant is in the opposite direction, github first then CRAN, CRAN doesn't have the latest changes right? Apologies for not being clear. 

```
#remove forestFloor
remove.packages("forestFloor")

#overwite with github bleeding edge (Rtools required for windows)
library(devtools)
install_github("sorhawell/forestFloor")

#install cran
install.packages("forestFloor")

#load library
library(forestFloor)

#your last pull request changes is present in installed version from github
deparse(forestFloor::Xtestmerger)[15:20]

[1] "    if (any(!namesCheck)) "                                                                                         
[2] "        stop(paste(\"column(s)\", which(!namesCheck), \"in Xtest and X has names mismatch. Col names must match\"))"
[3] "    factor.ind = which(sapply(X, is.factor))"                                                                       
[4] "    unmatchedTestLevels = mapply(FUN = function(xl, tl) tl[which(is.na(match(tl, "                                  
[5] "        xl)))], lapply(lapply(X[factor.ind], droplevels), levels), "                                                
[6] "        lapply(lapply(test[factor.ind], droplevels), levels), " 
```

It seems that the version change does not have any effect :(
```
#remove forestFloor
remove.packages("forestFloor")

#overwite with github bleeding edge (Rtools required for windows)
library(devtools)
install_github("rragundez/forestFloor") # here version is 1.11.2

#install cran
install.packages("forestFloor") # here version is 1.11.1

#load library
library(forestFloor)

#your last pull request changes is present in installed version from github
deparse(forestFloor::Xtestmerger)[15:20]

[1] "    if (any(!namesCheck)) "                                                                                         
[2] "        stop(paste(\"column(s)\", which(!namesCheck), \"in Xtest and X has names mismatch. Col names must match\"))"
[3] "    factor.ind = which(sapply(X, is.factor))"                                                                       
[4] "    unmatchedTestLevels = mapply(FUN = function(xl, tl) tl[which(is.na(match(tl, "                                  
[5] "        xl)))], lapply(lapply(X[factor.ind], droplevels), levels), "                                                
[6] "        lapply(lapply(test[factor.ind], droplevels), levels), "
```
Do you know when will the update be available in CRAN, there are several Analysts here and a cluster that needs the change :s, I am currently distributing the `.tar.gz` file but I am sure more than one will just go to the RStudio GUI and install from CRAN

**Comment by sorhawell** [comment]
So I have to manually submit a source tar.gz file CRAN to update the package. Because every CRAN update is reviewed by a living person and tested on their servers, they kindly ask not to submit too often. I have not updated CRAN since May, so if the solution below is not enough, I can push an update now.

```
library(devtools)
install_github("sorhawell/forestFloor")
```

**Comment by rragundez** [comment]
I understand, unfortunately all the machines are behind a proxy and `install_github` just hangs. I will try with distributing the `.tar.gz` package. Thanks a lot for the offer, I'll let you know

**Pull request merged**
